/**
 * Bloons TD Chinese content — towers, maps, skills, store, upgrades, PvP labels.
 * Load before bloons-td6-engine.js
 */
(function (global) {
  'use strict';

  var ZH = {
    towers: {
      dart_monkey: '飞镖猴',
      boomerang_monkey: '回旋镖猴',
      bomb_shooter: '炸弹射手',
      tack_shooter: '钉刺射手',
      ice_monkey: '冰块猴',
      glue_gunner: '胶水枪手',
      sniper_monkey: '狙击猴',
      monkey_sub: '潜水猴',
      monkey_buccaneer: '海盗猴',
      monkey_ace: '王牌飞行员',
      heli_pilot: '直升机飞行员',
      mortar_monkey: '迫击炮猴',
      dartling_gunner: '机枪猴',
      wizard_monkey: '法师猴',
      super_monkey: '超级猴',
      ninja_monkey: '忍者猴',
      alchemist: '炼金术士',
      druid: '德鲁伊',
      banana_farm: '香蕉农场',
      spike_factory: '刺钉工厂',
      monkey_village: '猴子村',
      engineer_monkey: '工程师猴',
      minecraft_monkey: '我的世界猴',
      roblox_monkey: 'Roblox猴',
      rng_monkey: '随机猴',
    },
    maps: {
      monkey_meadow: { name: '猴子草地', desc: '经典蜿蜒小路，带有水塘。' },
      tree_stump: { name: '树桩', desc: '气球绕着巨大树桩盘旋。' },
      town_center: { name: '城镇中心', desc: '广场街道与喷泉水域。' },
      scrapyard: { name: '废料场', desc: '垃圾堆挤占放置空间。' },
      the_cabin: { name: '小木屋', desc: '湖边小屋旁的温馨树林。' },
      resort: { name: '度假村', desc: '带大泳池的海滩度假区。' },
      lotus_island: { name: '莲花岛', desc: '环岛与莲花池。' },
      candy_falls: { name: '糖果瀑布', desc: '甜美的之字形下坡。' },
      winter_park: { name: '冬日公园', desc: '雪园中的冰道。' },
      carved: { name: '南瓜雕刻', desc: '万圣节南瓜地小路。' },
      park_path: { name: '公园小径', desc: '平缓的公园环线。' },
      alpine_run: { name: '高山跑道', desc: '山地之字弯道。' },
      frozen_over: { name: '冰封', desc: '结冰湖面上的细道。' },
      in_the_loop: { name: '循环之中', desc: '两条入口汇成一个出口。' },
      logs: { name: '原木', desc: '中间堆满原木。' },
      cubism: { name: '立体主义', desc: '直角块状艺术路径。' },
      balance: { name: '平衡', desc: '对称的阴阳双道。' },
      quiet_street: { name: '安静街道', desc: '郊区 S 弯。' },
      hedge: { name: '树篱', desc: '花园树篱迷宫。' },
      end_of_the_road: { name: '路的尽头', desc: '漫长沙漠公路与休息水塘。' },
      snake_river: { name: '蛇河', desc: '长长的蛇形弯道。' },
      tower_arena: { name: '塔防竞技场', desc: '开阔场地 — 足够放下所有猴子。' },
      cascade_falls: { name: '层叠瀑布', desc: '阶梯式落差与中央水塘。' },
      middle_of_the_road: { name: '路中央', desc: '十字路口 — 覆盖最关键。' },
      one_two_tree: { name: '一二三棵树', desc: '三座树岛分割赛道。' },
      crater: { name: '陨石坑', desc: '火山口边缘小路。' },
      streambed: { name: '河床', desc: '蜿蜒溪流，可放水上塔。' },
      chutes: { name: '滑道', desc: '工业滑槽赛道。' },
      spillway: { name: '溢洪道', desc: '泄洪水道。' },
      pats_pond: { name: '帕特池塘', desc: '池塘环绕的路线。' },
      peninsula: { name: '半岛', desc: '海边半岛地形。' },
      high_finance: { name: '高端金融', desc: '都市摩天楼街区。' },
      another_brick: { name: '另一块砖', desc: '砖墙迷宫。' },
      off_the_coast: { name: '离岸', desc: '近海航线。' },
      cornfield: { name: '玉米地', desc: '农田中的小路。' },
      underground: { name: '地下', desc: '洞穴通道。' },
      bamboo_loop: { name: '竹林环道', desc: '竹林环线。' },
      firing_range: { name: '射击场', desc: '军事训练场。' },
      encrypted: { name: '加密', desc: '赛博风格赛道。' },
      moab_alley: { name: '飞艇巷', desc: '专为难缠飞艇准备的城区。' },
      mesa: { name: '台地', desc: '沙漠台地。' },
      x_factor: { name: 'X 因子', desc: '交叉抽象路径。' },
      geared: { name: '齿轮', desc: '工业齿轮场地。' },
      sanctuary: { name: '圣所', desc: '神殿避难所。' },
      flooded_valley: { name: '洪水山谷', desc: '被水淹没的山谷。' },
      bloody_puddles: { name: '血色水坑', desc: '沼泽血洼。' },
      workshop: { name: '工坊', desc: '机械工坊。' },
      quad: { name: '四象', desc: '四向竞技场。' },
      dark_dungeons: { name: '黑暗地牢', desc: '阴暗地下城。' },
      dark_castle: { name: '黑暗城堡', desc: '专家级城堡防线。' },
      ouch: { name: '#哎哟', desc: '地狱级岩浆痛苦图。' },
      muddy_puddles: { name: '泥泞水坑', desc: '专家级泥潭。' },
      ravine: { name: '峡谷', desc: '陡峭峡谷。' },
      infernal: { name: '炼狱', desc: '岩浆炼狱。' },
      quarry: { name: '采石场', desc: '石料采场。' },
      covered_garden: { name: '廊架花园', desc: '有顶花园。' },
      bloontonium_lab: { name: '气球能源实验室', desc: '危险实验室。' },
    },
    branches: {
      Global: '全局',
      Primary: '初级',
      Military: '军事',
      Magic: '魔法',
      Support: '支援',
      Other: '其他',
    },
    knowledge: {
      more_cash: { name: '更多金钱', desc: '每局起始金钱 +100。' },
      tough_lives: { name: '坚韧生命', desc: '起始生命 +25。' },
      big_pockets: { name: '大口袋', desc: '起始金钱 +200。' },
      iron_will: { name: '钢铁意志', desc: '起始生命 +50。' },
      veteran_ops: { name: '老兵行动', desc: '所有塔伤害 +1。' },
      eagle_eye: { name: '鹰眼', desc: '所有塔射程 +15。' },
      quick_hands: { name: '快手', desc: '所有塔攻击速度加快 10%。' },
      sharper_shots: { name: '更锋利', desc: '所有塔穿透 +1。' },
      camo_radar: { name: '迷彩雷达', desc: '所有塔可侦测迷彩。' },
      heat_tips: { name: '灼热弹尖', desc: '所有塔可打破铅气球。' },
      bargain_bin: { name: '特价区', desc: '所有塔购买便宜 $20。' },
      smart_shopper: { name: '精明买家', desc: '升级便宜 10%。' },
      recycle: { name: '回收', desc: '出售退款 80%（原 70%）。' },
      round_bonus: { name: '回合奖励', desc: '每清完一回合 +50 金钱。' },
      knowledge_hustle: { name: '技能拼搏', desc: '每 5 回合额外 +1 技能点。' },
      cheap_darts: { name: '便宜飞镖', desc: '飞镖猴便宜 $25。' },
      dart_training: { name: '飞镖训练', desc: '飞镖猴穿透 +1。' },
      boomerang_budget: { name: '回旋镖预算', desc: '回旋镖猴便宜 $40。' },
      tack_swarm: { name: '钉刺风暴', desc: '钉刺射手攻击加快 15%。' },
      bomb_blast: { name: '更大爆炸', desc: '炸弹射手溅射 +15。' },
      ice_age: { name: '冰河时代', desc: '冰块猴冰冻时长 +0.6 秒。' },
      sticky_situation: { name: '黏糊状况', desc: '胶水枪手减速更强。' },
      primary_pro: { name: '初级专家', desc: '所有初级塔便宜 $35。' },
      military_intel: { name: '军事情报', desc: '所有军事塔可侦测迷彩。' },
      sniper_scope: { name: '狙击瞄准镜', desc: '狙击猴伤害 +2。' },
      submerged: { name: '潜入', desc: '潜水猴便宜 $50。' },
      air_support: { name: '空中支援', desc: '王牌与直升机穿透 +1。' },
      mortar_marksman: { name: '迫击炮神射', desc: '迫击炮溅射 +20。' },
      military_discount: { name: '军事折扣', desc: '所有军事塔便宜 $40。' },
      mana_shield: { name: '法力护盾', desc: '法师猴便宜 $40。' },
      ninja_discipline: { name: '忍者戒律', desc: '忍者攻击加快 12%。' },
      super_saver: { name: '超级省钱', desc: '超级猴便宜 $200。' },
      alchemy_101: { name: '炼金入门', desc: '炼金术士溅射 +12。' },
      druid_grove: { name: '德鲁伊林地', desc: '德鲁伊伤害 +1。' },
      magic_mastery: { name: '魔法精通', desc: '所有魔法塔便宜 $45。' },
      farm_boost: { name: '肥料', desc: '香蕉农场每秒 +5 金钱。' },
      farm_empire: { name: '农场帝国', desc: '香蕉农场再 +10$/秒。' },
      cheap_farms: { name: '便宜农场', desc: '香蕉农场便宜 $150。' },
      spike_stock: { name: '刺钉库存', desc: '刺钉工厂堆叠穿透 +3。' },
      village_vibes: { name: '村庄氛围', desc: '猴子村光环范围 +20。' },
      engineer_kit: { name: '工程师套件', desc: '工程师可多放 1 个哨兵。' },
      support_sale: { name: '支援特卖', desc: '所有支援塔便宜 $50。' },
    },
    store: {
      cash_boost: { name: '新手礼包', desc: '永久每局起始金钱 +150。' },
      gold_frame: { name: '金框', desc: '个人资料边框 — 在亚瑟个人资料徽章上装备。' },
      speed_pin: { name: '速度徽章', desc: '个人资料徽章 — 在亚瑟个人资料上装备。' },
    },
    bloonShop: {
      red1: '红',
      red10: '10 红',
      blue5: '5 蓝',
      green5: '5 绿',
      yellow5: '5 黄',
      pink5: '5 粉',
      black2: '2 黑',
      white2: '2 白',
      lead3: '3 铅',
      zebra2: '2 斑马',
      rainbow2: '2 彩虹',
      camo_pink: '8 迷彩粉',
      ceramic2: '2 陶瓷',
      moab: 'MOAB',
      bfb: 'BFB',
      ddt: 'DDT',
      zomg: 'ZOMG',
    },
    /* English upgrade name → Chinese (fallback = English if missing) */
    upgrades: {
      'Sharp Shots': '锋利射击',
      'Razor Sharp Shots': '剃刀锋利射击',
      'Spike-O-Pult': '刺钉投石机',
      Juggernaut: '主宰',
      'Ultra-Juggernaut': '超级主宰',
      'Long Range Darts': '远程飞镖',
      'Enhanced Eyesight': '强化视力',
      Crossbow: '十字弩',
      'Sharp Shooter': '神射手',
      'Crossbow Master': '十字弩大师',
      'Quick Shots': '快速射击',
      'Very Quick Shots': '超快射击',
      'Triple Shot': '三重射击',
      'Super Monkey Fan Club': '超级猴粉丝俱乐部',
      'Plasma Monkey Fan Club': '等离子猴粉丝俱乐部',
      'Improved Rangs': '强化回旋镖',
      'Glaive Ricochet': '刃盘弹射',
      'Glaive Lord': '刃盘领主',
      'Faster Throwing': '更快投掷',
      'Faster Rangs': '更快回旋镖',
      'Bionic Boomerang': '仿生回旋镖',
      'Turbo Charge': '涡轮加速',
      'Perma Charge': '永久充能',
      'Long Range Rangs': '远程回旋镖',
      'Red Hot Rangs': '赤热回旋镖',
      'Kylie Boomerang': '回旋标枪',
      'MOAB Press': '飞艇压制器',
      'MOAB Domination': '飞艇压制',
      'Bigger Bombs': '更大炸弹',
      'Heavy Bombs': '重型炸弹',
      'Really Big Bombs': '超大炸弹',
      'Bloon Impact': '气球冲击',
      'Bloon Crush': '气球粉碎',
      'Faster Reload': '更快装填',
      'Missile Launcher': '导弹发射器',
      'MOAB Mauler': '飞艇重击',
      'MOAB Assassin': '飞艇刺客',
      'MOAB Eliminator': '飞艇清除者',
      'Extra Range': '额外射程',
      'Frag Bombs': '破片炸弹',
      'Cluster Bombs': '集束炸弹',
      'Recursive Cluster': '递归集束',
      'Bomb Blitz': '炸弹闪击',
      'Faster Shooting': '更快射击',
      'Even Faster Shooting': '更快更快射击',
      'Tack Sprayer': '钉刺喷洒',
      Overdrive: '超频',
      'The Tack Zone': '钉刺领域',
      'Long Range Tacks': '远程钉刺',
      'Super Range Tacks': '超远钉刺',
      'Blade Shooter': '刀刃射手',
      'Blade Maelstrom': '刀刃漩涡',
      'Super Maelstrom': '超级漩涡',
      'More Tacks': '更多钉刺',
      'Even More Tacks': '更多更多钉刺',
      'Ring of Fire': '火环',
      'Inferno Ring': '炼狱环',
      Permafrost: '永冻',
      'Deep Freeze': '深度冰冻',
      'Arctic Wind': '北极之风',
      Snowstorm: '暴风雪',
      'Absolute Zero': '绝对零度',
      'Enhanced Freeze': '强化冰冻',
      'Metal Freeze': '金属冰冻',
      'Ice Shards': '冰晶碎片',
      Embrittlement: '脆化',
      'Super Brittle': '超级脆化',
      'Larger Radius': '更大范围',
      'Re-Freeze': '再冻结',
      'Cold Snap': '寒流',
      Icicles: '冰锥',
      'Icicle Impale': '冰锥穿刺',
      'Glue Soak': '胶水浸透',
      'Corrosive Glue': '腐蚀胶水',
      'Bloon Dissolver': '气球溶解',
      'Bloon Liquefier': '气球液化',
      'The Bloon Solver': '气球终结者',
      'Stickier Glue': '更黏胶水',
      'Stronger Glue': '更强胶水',
      'MOAB Glue': '飞艇胶水',
      'Relentless Glue': '无情胶水',
      'Super Glue': '超级胶水',
      'Glue Splash': '胶水溅射',
      'Glue Hose': '胶水软管',
      'Glue Strike': '胶水打击',
      'Glue Storm': '胶水风暴',
      'Full Metal Jacket': '全金属弹壳',
      'Large Calibre': '大口径',
      'Deadly Precision': '致命精准',
      'Maim MOAB': '重创飞艇',
      'Cripple MOAB': '瘫痪飞艇',
      'Night Vision Goggles': '夜视镜',
      'Shrapnel Shot': '破片弹',
      'Bouncing Bullet': '弹跳子弹',
      'Supply Drop': '空投补给',
      'Elite Sniper': '精英狙击',
      'Faster Firing': '更快开火',
      'Even Faster Firing': '更快更快开火',
      'Semi-Automatic': '半自动',
      'Full Auto Rifle': '全自动步枪',
      'Elite Defender': '精英防卫',
      'Longer Range': '更远射程',
      'Advanced Intel': '高级情报',
      'Submerge and Support': '潜水支援',
      'Bloontonium Reactor': '气球能源反应堆',
      Energizer: '增能器',
      'Barbed Darts': '倒刺飞镖',
      'Heat-tipped Darts': '灼热飞镖',
      'Ballistic Missile': '弹道导弹',
      'First Strike Capability': '先发打击',
      'Pre-emptive Strike': '先制打击',
      'Twin Guns': '双联装',
      'Airburst Darts': '空爆飞镖',
      'Advanced Targeting': '高级瞄准',
      'Sub Commander': '潜艇指挥官',
      'Grape Shot': '葡萄霰弹',
      'Hot Shot': '热弹',
      'Cannon Ship': '炮舰',
      'Monkey Pirates': '猴子海盗',
      'Pirate Lord': '海盗领主',
      'Longer Cannon': '更长炮管',
      "Crow's Nest": '瞭望台',
      Destroyer: '驱逐舰',
      'Aircraft Carrier': '航空母舰',
      'Carrier Flagship': '航母旗舰',
      Merchantman: '商船',
      'Favored Trades': '优惠贸易',
      'Trade Empire': '贸易帝国',
      'Rapid Fire': '连射',
      'Lots More Darts': '更多飞镖',
      'Fighter Plane': '战斗机',
      'Operation: Dart Storm': '飞镖风暴行动',
      'Sky Shredder': '天空撕裂者',
      'Spy Plane': '侦察机',
      'Centered Path': '居中航线',
      'Bomber Ace': '轰炸机王牌',
      'Ground Zero': '归零地',
      'Tsar Bomba': '沙皇炸弹',
      'Exploding Pineapple': '爆炸菠萝',
      'Sharper Darts': '更锋利飞镖',
      'Quad Darts': '四联飞镖',
      'Faster Engines': '更快引擎',
      'Bigger Jets': '更大喷气',
      IFR: '仪表飞行',
      Downdraft: '下洗气流',
      'Support Chinook': '支援支奴干',
      'Special Poperations': '特种行动',
      Pursuit: '追击',
      'Razor Rotors': '剃刀旋翼',
      'Apache Dartship': '阿帕奇飞镖舰',
      'Apache Prime': '阿帕奇至尊',
      'Bigger Blast': '更大爆炸',
      'Heavy Shells': '重型炮弹',
      'Signal Flare': '信号弹',
      'Artillery Battery': '炮兵连',
      'Pop and Awe': '震撼弹幕',
      'Burny Stuff': '燃烧物',
      'Shell Shock': '炮弹冲击',
      'The Biggest One': '最大一发',
      'Increased Accuracy': '精度提升',
      'Powerful Darts': '强力飞镖',
      Buckshot: '鹿弹',
      'Bloon Area Denial System': '气球区域拒止系统',
      'Bloon Exclusion Zone': '气球禁区',
      'Faster Barrel Spin': '更快枪管旋转',
      'Hydra Rocket Pods': '多头火箭吊舱',
      'Rocket Storm': '火箭风暴',
      'M.A.D': '疯狂毁灭',
      'Focused Firing': '集中射击',
      'Laser Shock': '激光冲击',
      'Laser Cannon': '激光炮',
      'Plasma Accelerator': '等离子加速器',
      'Ray of Doom': '末日射线',
      'Guided Magic': '制导魔法',
      'Arcane Blast': '奥术冲击',
      'Arcane Mastery': '奥术精通',
      'Arcane Spike': '奥术尖刺',
      Archmage: '大法师',
      'Wall of Fire': '火墙',
      "Dragon's Breath": '龙息',
      'Summon Phoenix': '召唤凤凰',
      'Wizard Lord Phoenix': '凤凰法师领主',
      'Intense Magic': '强化魔法',
      Fireball: '火球',
      'Laser Blast': '激光冲击',
      'Plasma Blast': '等离子冲击',
      'Sun Avatar': '太阳化身',
      'The Sun Temple': '太阳神庙',
      'True Sun God': '真·太阳神',
      'Super Range': '超远射程',
      'Epic Range': '史诗射程',
      'Robo Monkey': '机器猴',
      'Tech Terror': '科技恐惧',
      'The Anti-Bloon': '反气球者',
      Knockback: '击退',
      Ultravision: '超视觉',
      'Dark Knight': '黑暗骑士',
      'Dark Champion': '黑暗冠军',
      'Legend of the Night': '暗夜传说',
      'Ninja Discipline': '忍者戒律',
      'Sharp Shurikens': '锋利手里剑',
      'Double Shot': '双重射击',
      Bloonjitsu: '气球柔术',
      'Grandmaster Ninja': '忍者大师',
      Distraction: '干扰',
      'Counter-Espionage': '反间谍',
      'Shinobi Tactics': '忍术战术',
      'Bloon Sabotage': '气球破坏',
      'Grand Saboteur': '破坏宗师',
      'Seeking Shuriken': '追踪手里剑',
      Caltrops: '蒺藜',
      'Flash Bomb': '闪光弹',
      'Sticky Bomb': '黏性炸弹',
      'Master Bomber': '爆破大师',
      'Larger Potions': '更大药剂',
      'Acidic Mixture Dip': '酸性浸泡',
      'Berserker Brew': '狂战士药剂',
      'Stronger Stimulant': '更强兴奋剂',
      'Permanent Brew': '永久药剂',
      'Stronger Acid': '更强酸液',
      'Perishing Potions': '消亡药剂',
      'Unstable Concoction': '不稳定混合物',
      'Transforming Tonic': '变形补药',
      'Total Transformation': '完全变形',
      'Hardened Spikes': '硬化刺钉',
      'White Hot Spikes': '白热刺钉',
      'Spiked Balls': '刺球',
      'Spiked Mines': '刺雷',
      'Super Mines': '超级地雷',
      'Faster Production': '更快生产',
      'Even Faster Production': '更快更快生产',
      'MOAB-SHREDR Spikes': '飞艇粉碎刺钉',
      'Spike Storm': '刺钉风暴',
      'Carpet of Spikes': '刺钉地毯',
      'Long Reach': '长触及',
      'Smart Spikes': '智能刺钉',
      'Deadly Spikes': '致命刺钉',
      'Super Spikes': '超级刺钉',
      'Increased Production': '增产',
      'Greater Production': '更大增产',
      'Banana Plantation': '香蕉种植园',
      'Banana Republic': '香蕉共和国',
      'Banana Central': '香蕉中枢',
      'Long Life Bananas': '长寿香蕉',
      'Valuable Bananas': '高价香蕉',
      'Monkey Bank': '猴子银行',
      'IMF Loan': 'IMF 贷款',
      'Monkey-Nomics': '猴子经济学',
      'EZ Collect': '轻松收集',
      'Banana Salvage': '香蕉回收',
      Marketplace: '市场',
      'Central Market': '中央市场',
      'Monkey Wall Street': '猴子华尔街',
      'Larger Service Area': '更大服务区',
      'Jungle Drums': '丛林鼓',
      'Monkey Town': '猴子镇',
      'Monkey City': '猴子城',
      Monkeyopolis: '猴市',
      'Grow Blocker': '生长阻断',
      'Radar Scanner': '雷达扫描仪',
      'Monkey Intelligence Bureau': '猴子情报局',
      'Call to Arms': '战争号召',
      'Homeland Defense': '国土防御',
      'Sentry Gun': '哨兵枪',
      'Faster Engineering': '更快工程',
      Sprockets: '链轮',
      Overclock: '超频',
      Ultraboost: '超级加速',
      Deconstruction: '解构',
      'Cleansing Foam': '清洁泡沫',
      'Bloon Trap': '气球陷阱',
      'XXXL Trap': '超大陷阱',
      'Double Gun': '双枪',
      'Sentry Expert': '哨兵专家',
      'Sentry Empowerment': '哨兵赋能',
      'Sentry Champion': '哨兵冠军',
      'Hard Thorns': '坚硬荆棘',
      'Heart of Thunder': '雷霆之心',
      'Druid of the Storm': '风暴德鲁伊',
      'Ball Lightning': '球状闪电',
      Superstorm: '超级风暴',
      'Thorn Swarm': '荆棘群',
      'Druid of the Jungle': '丛林德鲁伊',
      "Jungle's Bounty": '丛林恩赐',
      'Spirit of the Forest': '森林之魂',
      'Heart of Oak': '橡木之心',
      'Druid of Wrath': '愤怒德鲁伊',
      'Avatar of Wrath': '愤怒化身',
    },
  };

  global.BTD6_ZH = ZH;
})(window);
